junit alaptesztek
BME-MIT-IET/iet-hf2021-aviato pull request #15
Opened 2021-05-04 21:36 UTC by DDorian13

Fix #14

2021-05-04 21:37 UTC, bitman07 requested changes

2021-05-04 21:37 UTC, bitman07 commented on Szkeleton/src/test/java/goldmapTeszt.java
> +}
Hiányos

2021-05-04 21:41 UTC, DDorian13 commented on Szkeleton/src/test/java/goldmapTeszt.java
> +}
Tudom, innen lesz a folytatás

2021-05-15 10:09 UTC, bitman07 approved these changes

2021-05-15 10:10 UTC, merged